using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.IO;
using System.Xml;
using System.Windows.Forms;
using System.Xml.Linq;

namespace MapEditor.Common
{
	public class ProjectData
	{
		public string gmxFilename = "";
		public string Src = "";
		public bool Saved = false;
		public bool Loaded = false;

		public EnvElement[] EnvElementsList = null;
		public EventElement[] EventElementsList = null;
		public EnvInstance[] EnvInstancesList = null;
		public EventInstance[] EventInstancesList = null;
		public GMItem allItems = null;

		public ProjectData(string srcPath)
		{
			Src = srcPath;
			gmxFilename = Path.GetFileName(srcPath);
			_readGMX();
			_saveProject();
		}

		private void _saveProject()
		{
			string path;
			path = Path.GetDirectoryName(Src);

			XmlDocument file = new XmlDocument();
			XmlComment comment = file.CreateComment("This Document is generated by Almora Map Editor, if you edit it by hand then you do so at your own risk!");
			XmlElement assets = file.CreateElement("assets");
			XmlElement options = file.CreateElement("options");

			List<XmlElement> optionsElements = new List<XmlElement>();

			options.AppendChild(_addXmlElement(file, "gmsProjectFile",gmxFilename));
			options.AppendChild(_addXmlElement(file, "gridEnabled", "0"));

			assets.AppendChild(options);

			file.AppendChild(comment);
			file.AppendChild(assets);

			file.Save(path + "\\" + Path.GetFileNameWithoutExtension(gmxFilename) + ".ame");
		}

		private XmlElement _addXmlElement(XmlDocument xml, string nodeName, string nodeValue)
		{
			XmlElement elem = xml.CreateElement(nodeName);
			elem.InnerText = nodeValue;
			return elem;
		}

		private void _readGMX()
		{
			XmlDocument XMLfile = new XmlDocument();
			XMLfile.Load(Src);

			string nodeElementsName;
			XmlNode root;
			allItems = new GMItem(Path.GetFileNameWithoutExtension(Path.GetFileNameWithoutExtension(gmxFilename)));
			string[] resTree = new string[] { "sprites", "backgrounds", "scripts", "objects", "rooms" };


			foreach (string nodeName in resTree)
			{
				try
				{
					root = XMLfile.SelectSingleNode("assets/" + nodeName);

					if (root == null)
					{
						return;
					}

					nodeElementsName = root.Attributes["name"].InnerText;

					//TreeNode main = treeViewGMX.Nodes.Add(fup(nodeElementsName), fup(nodeElementsName));

					GMItem main = new GMItem(nodeElementsName);
					allItems.add(main);

					_readSubNode(root, nodeName, nodeElementsName, main);
				}
				catch (Exception e)
				{
					MessageBox.Show(nodeName + ": " + e.Message);
				}
			}
		}

		private void _readSubNode(XmlNode node, string nodeName, string nodeElementsName, GMItem main)
		{
			foreach (XmlNode n in node)
			{
				if (n.Attributes["name"] != null)
				{
                    // group
					//TreeNode sub = main.Nodes.Add(n.Attributes["name"].InnerText);
					GMItem sub = new GMItem(n.Attributes["name"].InnerText);
					_readSubNode(n, nodeName, nodeElementsName, sub);
					main.add(sub);
				}
				else
				{
					//TreeNode sub = main.Nodes.Add(n.InnerText, Path.GetFileName(n.InnerText));
					//sub.ImageIndex = sub.SelectedImageIndex = 1;
					//sub.ContextMenuStrip = contextMenuStrip2;
					string name = (nodeName == "scripts") ? /*n.InnerText*/ Path.GetFileName(n.InnerText) /*+ ".gml"*/ : Path.GetFileName(n.InnerText)/*n.InnerText + "." + n.Name + ".gmx"*/;
					GMItem sub = new GMItem(name, nodeName);
					main.add(sub);
				}
			}
		}

		public void renderItemsTree(TreeView Tree)
		{
			Tree.Nodes.Clear();
			TreeNode NodeGM = Tree.Nodes.Add("NodeGM", "Project: " + Manager.Project.gmxFilename);
			Tree.Nodes.Add("NodeInternal", "Internal Files");

			//TreeNode t = treeViewGMX.Nodes["NodeGM"].Nodes.Add(Manager.Project.allItems.Name);
			Tree.ExpandAll();

			_treeAddGMItemGroup(NodeGM, Manager.Project.allItems.getSubitems());
		}

		private void _treeAddGMItemGroup(TreeNode t, List<GMItem> items)
		{
			foreach (GMItem item in items)
			{
				TreeNode newT = t.Nodes.Add(item.Name);
				if (item.isGroup)
				{
					newT.ImageIndex = 0;
					newT.SelectedImageIndex = 1;
					//newT.StateImageIndex = 2;
					_treeAddGMItemGroup(newT, item.getSubitems());
				}
				else
				{
					newT.ImageIndex = 3;
					switch (item.ResourceType)
					{
						case GMItemType.Background:
						case GMItemType.Sprite: newT.ImageIndex = 6; break;
						case GMItemType.Script: newT.ImageIndex = 5; break;
					}
					newT.SelectedImageIndex = newT.ImageIndex;
				}
			}
		}
	}
}
